name: Basic building and testing

on: [push]

jobs:
  build:	
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2
      - name: Get Java
        uses: actions/setup-java@v1
        with:
           java-version: '17'
      - name: Compiling
        run: |
          javac *.java
      - name: Running tests
        run: |
           java Tests
