name: Basic building and testing for OSX, Windows, Ubuntu

on: [push]

jobs:
  build:    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-latest
          - os: windows-latest            
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2
      - name: Get Java
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Compiling
        run: javac -d . src/*.java
      - name: Running tests
        run: java Tests
