name: Basic building and testing for OSX and Ubuntu (latest)

on: [push]

jobs:
  build:    
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-latest
          - os: windows-latest            
    steps:
      - name: Checkout reposiTtory content
        uses: actions/checkout@v2
      - name: Get Java
        uses: actions/setup-java@v1
        with:
           java-version: '17'
      - name: Compiling
        run: |
          javac *.java
      - name: Running tests
        run: |
           java Tests
